/* eslint no-param-reassign: 0 */

import { combineReducers } from 'redux';

/**
 * Combine app reducers
 * @see http://redux.js.org/docs/api/combineReducers.html
 *
 * @param  {Object} reducers
 * @return {Func}
 */
const appReducer = reducers => combineReducers({
  ...reducers,
});

/**
 * Delegates handling the action to the reducer generated by combineReducers().
 * However, whenever it receives USER_LOGOUT action, it returns the initial state all over again.
 * @see http://stackoverflow.com/questions/35622588/how-to-reset-the-state-of-a-redux-store
 *
 * @param  {Object} reducers
 * @return {Func}
 */
const rootReducer = reducers => ((state, action) => {
  if (action.type === 'USER_LOGOUT') {
    state = undefined;
  }
  return appReducer(reducers)(state, action);
});

export default rootReducer;
